"""
models.py – Pydantic data models shared across all services.
These are the canonical data contracts for the automation pipeline.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, HttpUrl


# ── Enums ─────────────────────────────────────────────────────────────────────

class PublishStatus(str, Enum):
    """Lifecycle state of a generated blog post."""
    PENDING = "pending"
    PUBLISHED = "published"
    SKIPPED = "skipped"
    FAILED = "failed"


class PublisherMode(str, Enum):
    """Supported publisher backends."""
    STATIC = "static"
    WORDPRESS = "wordpress"
    API = "api"


# ── Pinterest ─────────────────────────────────────────────────────────────────

class PinData(BaseModel):
    """Structured representation of a scraped Pinterest pin."""

    title: str
    description: str
    image_url: str
    pin_url: str
    topic: str
    keywords: List[str] = Field(default_factory=list)

    class Config:
        populate_by_name = True


# ── SEO Metadata ──────────────────────────────────────────────────────────────

class SEOMetadata(BaseModel):
    """All SEO fields generated by the AI writer."""

    seo_title: str
    slug: str
    meta_title: str = Field(max_length=60)
    meta_description: str = Field(max_length=160)
    focus_keyword: str
    secondary_keywords: List[str] = Field(min_length=5, max_length=15)
    pinterest_keywords: List[str] = Field(min_length=10, max_length=20)
    category: str
    tags: List[str] = Field(min_length=5, max_length=15)
    internal_links: List[str] = Field(default_factory=list)


# ── Pinterest Marketing ────────────────────────────────────────────────────────

class PinterestMarketing(BaseModel):
    """Pinterest-specific output for pin creation."""

    pin_title: str
    pin_description: str
    hashtags: List[str] = Field(min_length=10, max_length=20)
    social_caption: str


# ── Image Assets ──────────────────────────────────────────────────────────────

class ImageAsset(BaseModel):
    """A single image prompt with its alt text."""

    prompt: str
    alt_text: str
    label: str  # e.g. "featured", "step_1", "pinterest_pin"


# ── Blog Article ──────────────────────────────────────────────────────────────

class BlogArticle(BaseModel):
    """The full generated blog article and all its metadata."""

    # Source
    pin: PinData

    # SEO
    seo: SEOMetadata

    # Content
    markdown_content: str
    html_content: str = ""

    # Marketing
    pinterest: PinterestMarketing

    # Images
    images: List[ImageAsset] = Field(default_factory=list)

    # Tracking
    content_hash: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: PublishStatus = PublishStatus.PENDING
    published_url: str = ""


# ── Database Record ───────────────────────────────────────────────────────────

class ArticleRecord(BaseModel):
    """Flat record stored in SQLite."""

    id: Optional[int] = None
    title: str
    slug: str
    topic: str
    focus_keyword: str
    category: str
    pinterest_url: str
    content_hash: str
    status: PublishStatus = PublishStatus.PENDING
    published_url: str = ""
    published_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
